# Tomcat
server:
    port: 80
#    session:
#      timeout: 10
#    context-path: /
spring:
  # --数据库连接配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/zkvanet_hailuo
    username: root
    password: 123456
    #  --数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5  
    minIdle: 5  
    maxActive: 20  
    # 配置获取连接等待超时的时间
    maxWait: 60000  
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000  
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000  
    validationQuery: SELECT 1 FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat
  # -jpa配置；可逆向生成表
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
  #      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  #      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  # mvc模式相关配置
#  mvc:
#    view:
#      prefix: /view/
#      suffix: .jsp
  #  --文件上传大小；不设置默认是1MB
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb
  resources: # 指定静态资源的路径
          static-locations: classpath:/static/,classpath:/templates/
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
#    mode: HTML5
#    encoding: UTF-8
#    content-type: text/html # ;charset=<encoding> is added
#    cache: true # set to false for hot refresh
debug: false
# --mybatis相关配置
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.boot.pojo