spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456
#  --数据库连接池配置
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5  
    minIdle: 5  
    maxActive: 20  
    # 配置获取连接等待超时的时间
    maxWait: 60000  
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000  
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000  
    validationQuery: SELECT 1 FROMDUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat
# -jpa配置；可逆向生成表
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
#  --文件上传大小；不设置默认是1MB
  http:
    multipart:
      maxFileSize: 100Mb
      maxRequestSize: 100Mb
server:
  port: 80

debug: false
mybatis:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.boot.pojo